# Copyright (c) 2019 R. Tohid
#
# Distributed under the Boost Software License, Version 1.0. (See a copy at
# http://www.boost.org/LICENSE_1_0.txt)

version: '3'

services:
    flecsi:
        build:
            context: .
            dockerfile: Dockerfile
        # command: 
        image: flecsi-project
        user: stellar:stellar
        container_name: flecsi-stellar
        volumes:
            - ./spack:/home/stellar/src/spack
            - ./scripts/vimrc:/home/stellar/.vimrc
        restart: on-failure
